### ISSUE TITLE
Swimming Events View

### ISSUE THREAD

**Issue by AndreasVikke** [AndreasVikke/Delfin-Sv-mmeklub#31]
Database (id, name, participants(SSN), ...)
DataAccessor
Show All GUI
Create GUI
Link Events to Results

**Comment by NinaLisakowski** [comment]
CREATE TABLE `event` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(55) NOT NULL,
  `date` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4
